### ISSUE TITLE
no strong name on NeoSmart.Unicode

### ISSUE THREAD

**Issue by taranais** [neosmart/unicode.net#1]
> No se puede cargar el archivo o ensamblado 'NeoSmart.Unicode, Version=0.1.2.0, Culture=neutral, PublicKeyToken=null' ni una de sus dependencias. Se necesita un ensamblado con nombre seguro. (Excepción de HRESULT: 0x80131044)

**Comment by tellarin** [comment]
@mqudsi, do you folks plan to strong name the DLLs in the nuget package?

**Comment by mqudsi** [comment]
@tellarin do you know what approach the open source community has generally adopted in this regard? Is there a nuget-specific recommendation?

**Comment by tellarin** [comment]
@mqudsi, unfortunately I'm not aware of a default solution for open source projects. But "strong naming" only requires a certificate owned by the project.
Code-signing or package signing may be a little more complicated to implement/control.
