### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by igitur** [neosmart/unicode.net#14]
Hi,

Microsoft now recommends that assemblies be strong named. See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md . 

Would you be able to strong name this and release an updated version to NuGet? If you don't have capacity, I can prepare a PR.

thanks

**Comment by mqudsi** [comment]
The project was updated to be signed with a strong name some years ago but a release was never pushed out to nuget. 

I have just published 0.1.3, can you check and let me know if it solves the problem?

**Comment by igitur** [comment]
Perfect, thanks. It solves my problem.

**Comment by mqudsi** [comment]
Thanks for the confirmation and for prodding me into getting a signed release out. I presume you needed it as a dependency to a different strongly-signed project?

**Comment by igitur** [comment]
Yes, for Emoji support in ClosedXML.

https://github.com/ClosedXML/ClosedXML/pull/1231
