### ISSUE TITLE
Distinguish emoji: house and houses

### ISSUE THREAD

**Issue by ya-erm** [neosmart/unicode.net#17]
Those emoji should be different:
🏠 - House (https://emojipedia.org/house/)
🏘 - Houses / House Buildings (https://emojipedia.org/houses/)

But now `Emoji.House` returns Houses emoji
https://github.com/neosmart/unicode.net/blob/982672213a4c291d33cf61afbcc25eb466e1dc51/unicode/Emoji-All.cs#L1756

**Comment by mqudsi** [comment]
Hello @ya-erm and thanks for the bug report!

My first thought was that the missing emoji was from a newer Unicode TR, and while indeed `House` is from Unicode 6.0 and `Houses` is from Unicode 7.0 (four years later), both those versions are supported.

We use an algorithm [to heuristically clean up the names](https://github.com/neosmart/unicode.net/blob/982672213a4c291d33cf61afbcc25eb466e1dc51/importers/importer.ts#L17) in the Unicode TR data to normalize the input, it's possible that it's clobbering the two values into one.

**Comment by mqudsi** [comment]
Actually, it's more complicated than that. The raw data that the current release was generated against [is here](https://github.com/neosmart/unicode.net/blob/9826722/importers/emoji-test.txt), and you can see the definitions in the file:

Houses:

https://github.com/neosmart/unicode.net/blob/982672213a4c291d33cf61afbcc25eb466e1dc51/importers/emoji-test.txt#L2432

House:

https://github.com/neosmart/unicode.net/blob/982672213a4c291d33cf61afbcc25eb466e1dc51/importers/emoji-test.txt#L2438

The UTR lists both using the same name, and we're not manually distinguishing between them.

**Comment by mqudsi** [comment]
The file [`emoji-variation-sequence.txt`](https://www.unicode.org/Public/13.0.0/ucd/emoji/emoji-variation-sequences.txt) contains data that can be used to distinguish between them further.

**Comment by mqudsi** [comment]
A new version of the package has been uploaded to nuget.org with the fix for this issue.
