### ISSUE TITLE
Lacking Emoji 0x1f970 Smiling Face With Hearths !

### ISSUE THREAD

**Issue by andy-soft** [neosmart/unicode.net#20]
please add this code and the unicode range as well!

 /* 🥰 */
        public static readonly SingleEmoji SmilingFaceWithHearths = new SingleEmoji(
                sequence: new UnicodeSequence(0x1f970),
                name: "smiling face",
                group: "Smileys & People",
                subgroup: "face-positive",
                searchTerms: new[] { "smiling", "face", "with", "hearths" },
                sortOrder: 50
            );

**Comment by mqudsi** [comment]
I just merged the upgrade to unicode 13 into git master, this should now be supported.

Purely out of curiosity and so I can understand our users, may I ask how you found this project and what you are using it for?

**Comment by mqudsi** [comment]
A new version of the package has been uploaded to nuget.org with the fix.

**Comment by andy-soft** [comment]
> I just merged the upgrade to unicode 13 into git master, this should now be supported.
> 
> Purely out of curiosity and so I can understand our users, may I ask how you found this project and what you are using it for?
I am currently involved in a Project which analyzes text written into chat systems (like chatbots) and I saw people react to conversations including some emojis (both types: the unicode ones, and the character-built ones)
So I began to write support for this chat-types, I went to Unicode.org, then googled and doodles a while until your project popped up! 

I currently don't use your routine unless for having the Emoji-database ripped out at startup, creating an emoji-trie structure to parse out the variable-length emoji sequences from a Unicode stream. 
This originally failed on your routines, please check your IsEmoji and CodePoint Unicode set-routines (I re-wrote some of them for better results in my system) BTW: you need to upgrade also the ranges on the static RANGE variable for many more characters! (and also there are other emojis lacking!)
About the Project 

My project is a framework to create Virtual Persona (Agents) which are really smart out-of-the=box, unlike trainable chatbots.

Our framework's software performs heavy NLP processing and many AI-based processes, 

We created and use a new language called DDL (Dialog Description Language) which is our invention: we defined it, created the specs, then the compiler as well as a full-blown debugger for this non- Von-Neuman language.

There on the NLP parser, I use the emojis group and subgroup names and the description words behind the emojis, from them doing a little NLP I rescue the sentiment and main topic of each emoji. This allows me to answer emotionally in a sentimental-aware way.

On our framework we do emotional evaluation of phrases based on fuzzy-8 phase sentiment-vectors, (see Robert Plutckik's emotion wheel). This allows our Virtual Persona to interact empathetically with humans, enhancing the quality of interaction.

Check our website, (it's in Spanish and some things are in English)
https://api.adipta.co/turnos

My company is on: adipta.co 

Thanks a lot for your work.

**Comment by mqudsi** [comment]
Hey, thanks for the info and interesting idea. 

The ranges have also been updated in this release, you can check to see if it fixes the problem you had. Both the ranges and the emoji were from Unicode 5, but the latest release uses Unicode 13 with all the newest emoji and updates the ranges accordingly.
