### ISSUE TITLE
SingleEmoji.Equals(SingleEmoji x, SingleEmoji y)

### ISSUE THREAD

**Issue by COM8** [neosmart/unicode.net#4]
https://github.com/neosmart/unicode.net/blob/3b0bd1867c96221b344084d8d82278f7c6a812b8/unicode/SingleEmoji.cs#L32

Shouldn't this be `return x.Sequence == y.Sequence;`?

I will create a PR for this.

**Comment by mqudsi** [comment]
No, that method shouldn't exist. There should be a `static` `Equals` function taking two `SingleEmoji` instances as parameters and a non-`static` member function taking one `SingleEmoji` parameter. It should also implement `IEquatable<SingleEmoji>`.

**Comment by COM8** [comment]
> 
> 
> No, that method shouldn't exist. There should be a `static` `Equals` function taking two `SingleEmoji` instances as parameters and a non-`static` member function taking one `SingleEmoji` parameter. It should also implement `IEquatable<SingleEmoji>`.

Will update my PR and fix this for `SingleEmoji` and `UnicodeSequence`

**Comment by COM8** [comment]
`IEqualityComparer<SingleEmoji>` requires it to exist.
I keept it and added one in the `UnicodeSequence` class.

ee5fed0 Should fix this.
