### ISSUE TITLE
SingleEmoji issue collection

### ISSUE THREAD

**Issue by COM8** [neosmart/unicode.net#5]
The following methods do not handle `null` values.

https://github.com/neosmart/unicode.net/blob/3b0bd1867c96221b344084d8d82278f7c6a812b8/unicode/SingleEmoji.cs#L25

https://github.com/neosmart/unicode.net/blob/3b0bd1867c96221b344084d8d82278f7c6a812b8/unicode/SingleEmoji.cs#L30

https://github.com/neosmart/unicode.net/blob/3b0bd1867c96221b344084d8d82278f7c6a812b8/unicode/SingleEmoji.cs#L40

https://github.com/neosmart/unicode.net/blob/3b0bd1867c96221b344084d8d82278f7c6a812b8/unicode/SingleEmoji.cs#L45

https://github.com/neosmart/unicode.net/blob/3b0bd1867c96221b344084d8d82278f7c6a812b8/unicode/SingleEmoji.cs#L37
Should be: `return obj.GetHashCode();`

I will create a PR for all of those bugs.

**Comment by mqudsi** [comment]
@COM8 thanks for taking the time to file this. I actually don't see why `SingleEmoji` can't be a `struct`.

**Comment by COM8** [comment]
Ok I changed it to a struct.
Any reason [UnicodeSequence](https://github.com/UWPX/unicode.net/blob/master/unicode/UnicodeSequence.cs) is no struct?
Or should I change it too?

**Comment by mqudsi** [comment]
It can *probably* be made a `struct` as well; I think it was for nullability on .NET 2.0 without `Nullable<T>` but I'm planning on dropping support for legacy platforms to update `unicode.net` to use `Span<T>` for huge performance wins.

Thanks!
