### ISSUE TITLE
SingleEmoji CompareTo(...)

### ISSUE THREAD

**Issue by COM8** [neosmart/unicode.net#8]
https://github.com/neosmart/unicode.net/blob/cb736197e1549a6229a7351e3d11212684a2f484/unicode/SingleEmoji.cs#L30-L33

It's using the underlaying `UnicodeSequence` as referene for comparison.
Shouldn't we use `SortOrder` here instead?
```C#
public int CompareTo(SingleEmoji other)
{
    return SortOrder.CompareTo(other.SortOrder);
}
```
At the moment all emoji lists are not rellay sorted any more like they were.

**Comment by mqudsi** [comment]
Yup, you're right. My mistake.

I'll fix that and add a regression test.
