### ISSUE TITLE
Fitzpatrick modifiers issue

### ISSUE THREAD

**Issue by COM8** [neosmart/unicode.net#9]
https://github.com/neosmart/unicode.net/blob/1c2f93e9e94e8e7be2df1385afcfe4efae79c85c/unicode/Emoji.cs#L33

Based on [Wikipedia](https://en.wikipedia.org/wiki/Fitzpatrick_scale) and [Emojipedia](https://emojipedia.org/emoji-modifier-fitzpatrick-type-1-2/) this line should be:
```C#
public static readonly Codepoint Fitzpatrick12 = Light;
```

**Comment by mqudsi** [comment]
Thanks for catching it. It's funny, the duplication of `MediumLight` between 

https://github.com/neosmart/unicode.net/blob/1c2f93e9e94e8e7be2df1385afcfe4efae79c85c/unicode/Emoji.cs#L33

and 

https://github.com/neosmart/unicode.net/blob/1c2f93e9e94e8e7be2df1385afcfe4efae79c85c/unicode/Emoji.cs#L35

actually caught my eye the other day and I told myself to look into it when I get the chance, as it looked suspiciously like a copy-and-paste error (except in reverse).
